set_property IOSTANDARD LVCMOS33 [get_ports {seg_enable[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_enable[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_enable[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_enable[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_enable[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_enable[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_enable[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_enable[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_tube[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_tube[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_tube[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_tube[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_tube[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_tube[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_tube[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports switch_en]
set_property IOSTANDARD LVCMOS33 [get_ports {col_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {col_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {col_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {col_out[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {row_in[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {row_in[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {row_in[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {row_in[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports cpu_pause_led]
set_property IOSTANDARD LVCMOS33 [get_ports input_complete_led]
set_property IOSTANDARD LVCMOS33 [get_ports {input_state[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {input_state[1]}]

set_property IOSTANDARD LVCMOS33 [get_ports {switch_map[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch_map[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch_map[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch_map[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch_map[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch_map[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch_map[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch_map[0]}]

#################################################################

set_property PACKAGE_PIN A18 [get_ports {seg_enable[7]}]
set_property PACKAGE_PIN A20 [get_ports {seg_enable[6]}]
set_property PACKAGE_PIN B20 [get_ports {seg_enable[5]}]
set_property PACKAGE_PIN E18 [get_ports {seg_enable[4]}]
set_property PACKAGE_PIN F18 [get_ports {seg_enable[3]}]
set_property PACKAGE_PIN D19 [get_ports {seg_enable[2]}]
set_property PACKAGE_PIN E19 [get_ports {seg_enable[1]}]
set_property PACKAGE_PIN C19 [get_ports {seg_enable[0]}]

set_property PACKAGE_PIN C15 [get_ports {seg_tube[6]}]
set_property PACKAGE_PIN C14 [get_ports {seg_tube[5]}]
set_property PACKAGE_PIN E17 [get_ports {seg_tube[4]}]
set_property PACKAGE_PIN F16 [get_ports {seg_tube[3]}]
set_property PACKAGE_PIN F14 [get_ports {seg_tube[2]}]
set_property PACKAGE_PIN F13 [get_ports {seg_tube[1]}]
set_property PACKAGE_PIN F15 [get_ports {seg_tube[0]}]

set_property PACKAGE_PIN Y18 [get_ports clk]
set_property PACKAGE_PIN W4 [get_ports rst_n]
set_property PACKAGE_PIN W9 [get_ports switch_en]

set_property PACKAGE_PIN M2 [get_ports {col_out[3]}]
set_property PACKAGE_PIN K6 [get_ports {col_out[2]}]
set_property PACKAGE_PIN J6 [get_ports {col_out[1]}]
set_property PACKAGE_PIN L5 [get_ports {col_out[0]}]

set_property PACKAGE_PIN K4 [get_ports {row_in[3]}]
set_property PACKAGE_PIN J4 [get_ports {row_in[2]}]
set_property PACKAGE_PIN L3 [get_ports {row_in[1]}]
set_property PACKAGE_PIN K3 [get_ports {row_in[0]}]
set_property PULLUP true [get_ports {row_in[0]}]
set_property PULLUP true [get_ports {row_in[1]}]
set_property PULLUP true [get_ports {row_in[2]}]
set_property PULLUP true [get_ports {row_in[3]}]

set_property PACKAGE_PIN K17 [get_ports cpu_pause_led]
set_property PACKAGE_PIN L13 [get_ports input_complete_led]
set_property PACKAGE_PIN E22 [get_ports {input_state[0]}]
set_property PACKAGE_PIN A21 [get_ports {input_state[1]}]

set_property PACKAGE_PIN Y9 [get_ports {switch_map[7]}]
set_property PACKAGE_PIN W9 [get_ports {switch_map[6]}]
set_property PACKAGE_PIN Y7 [get_ports {switch_map[5]}]
set_property PACKAGE_PIN Y8 [get_ports {switch_map[4]}]
set_property PACKAGE_PIN AB8 [get_ports {switch_map[3]}]
set_property PACKAGE_PIN AA8 [get_ports {switch_map[2]}]
set_property PACKAGE_PIN V8 [get_ports {switch_map[1]}]
set_property PACKAGE_PIN V9 [get_ports {switch_map[0]}]
